[pytest]
pythonpath = ./python/src ./python/src/neet_code_150
addopts = --import-mode=importlib
filterwarnings =
    ignore:.*UnionGenericAlias.*:DeprecationWarning
    ignore:BaseAgentConfig is deprecated:DeprecationWarning
    ignore:\[EXPERIMENTAL\] feature.*:UserWarning